# Generated by Django 3.2.25 on 2025-01-16 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('machine_number', models.CharField(max_length=50)),
                ('machine_type', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('production_year', models.CharField(max_length=50)),
                ('expiration_year', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='management.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operators', to='management.company')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MachineParameter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('injection_temperature', models.CharField(max_length=50)),
                ('mold_temperature', models.CharField(max_length=50)),
                ('clamping_force', models.CharField(max_length=50)),
                ('injection_pressure', models.CharField(max_length=50)),
                ('cooling_time', models.CharField(max_length=50)),
                ('velocity', models.CharField(max_length=50)),
                ('hot_runner_temperature', models.CharField(max_length=50)),
                ('decompression', models.CharField(max_length=50)),
                ('rotation_speed_of_screw', models.CharField(max_length=50)),
                ('hold_pressure', models.CharField(max_length=50)),
                ('hold_velocity', models.CharField(max_length=50)),
                ('hold_time', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('back_pressure', models.CharField(max_length=50)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parameters', to='management.machine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.customer'),
        ),
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('urgency', models.CharField(choices=[('Not Urgent', 'Not Urgent'), ('Urgent', 'Urgent'), ('Very Urgent', 'Very Urgent')], max_length=50)),
                ('status', models.CharField(choices=[('Not yet', 'Not yet'), ('Resolved', 'Resolved')], max_length=50)),
                ('description', models.TextField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.customer')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.machine')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.operator')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
