# Generated by Django 3.2.25 on 2025-01-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='machine_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='machine_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='machine',
            name='name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
    ]
