# Generated by Django 3.2.25 on 2025-02-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20250117_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='machineparameter',
            name='machine',
        ),
        migrations.DeleteModel(
            name='BugReport',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='MachineParameter',
        ),
    ]
