# Generated by Django 3.2.25 on 2025-06-05 11:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import management.helpers.storage
import management.helpers.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0004_remove_company_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_file', models.FileField(blank=True, null=True, storage=management.helpers.storage.DocumentS3Storage(), upload_to=management.helpers.utils.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), management.helpers.utils.document_file_size])),
                ('document_name', models.CharField(max_length=255)),
                ('document_tag', models.CharField(max_length=100)),
                ('document_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('document_description', models.TextField(blank=True, null=True)),
                ('text_index_name', models.CharField(max_length=255)),
                ('image_index_name', models.CharField(max_length=255)),
                ('progress', models.FloatField(default=0.0)),
                ('job_id', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
