# Generated by Django 3.2.25 on 2025-06-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='image_index_name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='text_index_name',
        ),
    ]
