# Generated by Django 3.2.25 on 2025-06-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_document_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image_upserted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='table_upserted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='text_upserted',
            field=models.BooleanField(default=False),
        ),
    ]
