# Generated by Django 3.2.25 on 2025-06-24 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20250611_0442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='image_upserted',
            new_name='image_status',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='table_upserted',
            new_name='table_status',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='text_upserted',
            new_name='text_status',
        ),
    ]
