# Generated by Django 3.2.25 on 2025-06-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20250624_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='image_status',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='table_status',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='text_status',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
