# Generated by Django 3.2.25 on 2025-07-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_company_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='image_status',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='document',
            name='table_status',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='document',
            name='text_status',
            field=models.CharField(max_length=80),
        ),
    ]
