# Generated by Django 3.2.25 on 2025-07-01 18:36

import django.core.validators
from django.db import migrations
import management.helpers.custom_filefield
import management.helpers.utils


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20250701_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=management.helpers.custom_filefield.DynamicStorageFileField(blank=True, null=True, upload_to=management.helpers.utils.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), management.helpers.utils.document_file_size]),
        ),
    ]
