# Generated by Django 3.2.25 on 2025-07-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_document_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
