# Generated by Django 3.2.25 on 2025-07-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_alter_document_document_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='job_created_at',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
