# Generated by Django 3.2.25 on 2025-07-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_document_job_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
