# Generated by Django 3.2.25 on 2025-01-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemessage',
            name='machine_model',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagemessage',
            name='sender',
            field=models.CharField(choices=[('U', 'user'), ('A', 'ai_agent')], default='user', max_length=9),
        ),
        migrations.AddField(
            model_name='textmessage',
            name='machine_model',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textmessage',
            name='sender',
            field=models.CharField(choices=[('U', 'user'), ('A', 'ai_agent')], default='user', max_length=9),
        ),
    ]
