# Generated by Django 3.2.25 on 2025-02-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbot', '0002_auto_20250131_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemessage',
            name='machine_model',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='textmessage',
            name='machine_model',
            field=models.CharField(max_length=255),
        ),
    ]
