# Generated by Django 3.2.25 on 2025-02-06 13:11

import django.core.validators
from django.db import migrations, models
import zbot.helpers.utils


class Migration(migrations.Migration):

    dependencies = [
        ('zbot', '0003_auto_20250203_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemessage',
            name='image',
            field=models.ImageField(null=True, upload_to='v1/static/media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg']), zbot.helpers.utils.file_size]),
        ),
        migrations.AlterField(
            model_name='imagemessage',
            name='metadata',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='imagemessage',
            name='sender',
            field=models.CharField(choices=[('U', 'user'), ('A', 'ai')], default='user', max_length=9),
        ),
        migrations.AlterField(
            model_name='textmessage',
            name='sender',
            field=models.CharField(choices=[('U', 'user'), ('A', 'ai')], default='user', max_length=9),
        ),
    ]
