# Generated by Django 3.2.25 on 2025-02-11 21:15

import django.core.validators
from django.db import migrations
import zbot.helpers.utils
import zbot.models


class Migration(migrations.Migration):

    dependencies = [
        ('zbot', '0004_auto_20250206_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemessage',
            name='image',
            field=zbot.models.CustomImageField(null=True, upload_to='v1/static/media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg']), zbot.helpers.utils.file_size]),
        ),
    ]
