# Generated by Django 3.2.25 on 2025-02-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbot', '0005_alter_imagemessage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemessage',
            name='image_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
