# Generated by Django 3.2.25 on 2025-02-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbot', '0006_imagemessage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemessage',
            name='sender',
            field=models.CharField(choices=[('user', 'user'), ('ai', 'ai')], default='user', max_length=9),
        ),
        migrations.AlterField(
            model_name='textmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'user'), ('ai', 'ai')], default='user', max_length=9),
        ),
    ]
