# Generated by Django 3.2.25 on 2025-02-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbot', '0007_auto_20250213_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemessage',
            name='metadata',
            field=models.TextField(blank=True, null=True),
        ),
    ]
