# Generated by Django 3.2.25 on 2025-02-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbot', '0009_auto_20250224_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='qauntity',
            new_name='melt_density',
        ),
        migrations.RemoveField(
            model_name='material',
            name='name',
        ),
        migrations.AddField(
            model_name='machine',
            name='def_clamping_force',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='machine',
            name='def_doc_index',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='def_images_index',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='def_injection_pressure',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='machine',
            name='def_max_sys_pressure',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='machine',
            name='def_mold_thickness',
            field=models.CharField(default=0.0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='def_screw_diameter',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='machine',
            name='def_screw_stroke',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='machine',
            name='def_shot_volume',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='machine',
            name='def_space_tie_bars',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='machine',
            name='expiration_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='production_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
