# Generated by Django 3.2.25 on 2025-02-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbot', '0010_auto_20250225_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineparameter',
            name='decompression',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='machineparameter',
            name='hot_runner_temperature',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='machineparameter',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
