# Generated by Django 3.2.25 on 2025-02-25 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zbot', '0011_auto_20250225_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='owner',
            new_name='company',
        ),
        migrations.AddField(
            model_name='machineparameter',
            name='conversation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='parameters', to='zbot.conversation'),
            preserve_default=False,
        ),
    ]
