# Generated by Django 3.2.25 on 2025-02-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbot', '0012_auto_20250225_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineparameter',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
