# Generated by Django 3.2.25 on 2025-03-02 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zbot', '0014_conversation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineparameter',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zbot.conversation'),
        ),
        migrations.AlterField(
            model_name='machineparameter',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zbot.machine'),
        ),
        migrations.AlterField(
            model_name='machineparameter',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zbot.material'),
        ),
    ]
