# Generated by Django 3.2.25 on 2025-06-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbot', '0015_auto_20250302_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemessage',
            name='top_k',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='imagemessage',
            name='machine_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
