# Generated by Django 3.2.25 on 2025-06-12 17:30

import django.core.validators
from django.db import migrations
import zbot.helpers.storage
import zbot.helpers.utils
import zbot.models


class Migration(migrations.Migration):

    dependencies = [
        ('zbot', '0016_auto_20250612_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemessage',
            name='image',
            field=zbot.models.CustomImageField(blank=True, null=True, storage=zbot.helpers.storage.ImageS3Storage(), upload_to=zbot.helpers.utils.image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'heic']), zbot.helpers.utils.image_file_size]),
        ),
    ]
