# Generated by Django 3.2.25 on 2025-06-29 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zbot', '0017_alter_imagemessage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineparameter',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zbot.conversation'),
        ),
        migrations.AlterField(
            model_name='machineparameter',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zbot.machine'),
        ),
        migrations.AlterField(
            model_name='machineparameter',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zbot.material'),
        ),
    ]
